# state.py
# Defines the shared state structure passed between all LangGraph nodes

from typing import TypedDict, Optional, List

class SupportState(TypedDict):
    """
    Central state object that flows through the entire LangGraph workflow.
    Every node reads from and writes to this state.
    """
    customer_id: str                  # Unique customer identifier
    customer_name: str                # Customer's name
    query: str                        # Original customer query
    intent: str                       # Classified intent: Sales/Technical/Billing/Account/Memory
    department: str                   # Routed department
    retrieved_context: str            # Context retrieved from RAG pipeline
    requires_approval: bool           # True if human approval is needed
    approval_status: str              # "pending", "approved", "rejected"
    agent_response: str               # Response generated by department agent
    supervisor_response: str          # Response after supervisor review
    final_response: str               # Final response sent to customer
    conversation_history: List[dict]  # List of past interactions from memory
    error: Optional[str]              # Any error messages